# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
tarmac = "rojo-rbx/tarmac@0.7.3"
remodel = "rojo-rbx/remodel@0.11.0"
