name = "Tyiler"

# since the upload limit can be bypassed by just uploading to different groups that are all related,
# once you hit the monthly limit, just change group IDs and keep uploading!
# StarSim: 6896773
# GAR: 6897077
upload-to-group-id = 6897077

[[inputs]]
glob = "**/*tile*.png"
codegen = true
codegen-path = "MapTiles.lua"